plumdog/flask_table

flask_table/table.py
tests/__init__.py
tests/html/thead_class_test/test_one.html

Add option for setting a thead class

---

flask_table/table.py
tests/__init__.py
tests/html/dynamic_cols_inherit_test/test_one.html

Inherit columns when inheriting a parent table class

---

tests/html/datetime_test/test_one.html

It looks like Babel has updated the definitions, or - in fact - I think that the CLDR has been updated.

Fix tests for update to Babel

---

README
README.md

To better document the way the different column types work and their options. Inspired by #19.

Add better docs for the column types

---

flask_table/columns.py
tests/__init__.py
tests/html/datetime_test_format/test_one.html

Fix DatetimeCol format option

---

README.md
examples/simple_nested.py
flask_table/__init__.py
flask_table/columns.py
tests/__init__.py
tests/html/nestedcol_test/test_one.html

As discussed in #27 the ability to nest tables within tables is a very useful and common feature. This PR attempts to provide such functionality.

Add support for nesting tables via NestedTableCol type

---

flask_table/table.py
tests/__init__.py
tests/html/no_items_allow_empty/test_zero.html

Add option to allow empty table

---

tests/__init__.py

Force env vars before imports in tests

---

README.md
flask_table/columns.py
tests/__init__.py
tests/html/bool_test/test_one_custom_display.html

Customisable BoolCol display values

---

flask_table/__init__.py
flask_table/columns.py
tests/__init__.py
tests/html/bool_test/test_one_na.html

Add BoolNaCol

---

flask_table/table.py
requirements.txt

Modify deprecated babel package

---

flask_table/columns.py
tests/__init__.py

Remove any flask.ext imports

---

README.md
examples/column_html_attrs.py
flask_table/columns.py
flask_table/table.py
tests/__init__.py
tests/html/column_html_attrs_test/test_both_html_attrs.html
tests/html/column_html_attrs_test/test_column_html_attrs.html
tests/html/column_html_attrs_test/test_overwrite_attrs.html
tests/html/column_html_attrs_test/test_td_html_attrs.html
tests/html/column_html_attrs_test/test_th_html_attrs.html

Add column_html_attrs, td_html_attrs and th_html_attrs kwargs to Col

---

README.md
flask_table/columns.py
tests/__init__.py
tests/html/link_test/test_one_attrs.html

Add link attrs as mentioned #55

Add link attrs 

---

README.md
flask_table/table.py
tests/__init__.py
tests/html/html_attrs_test/test_html_attrs.html

Sort out html_attrs

---

README.md

Better docs for table options

---

README.md
flask_table/columns.py
tests/__init__.py
tests/html/button_form_attrs_test/test_one.html

ButtonCol form attributes

---

README.md
flask_table/columns.py
flask_table/html.py
tests/__init__.py
tests/html/button_hidden_fields_test/test_one.html

ButtonCol form hidden fields

---

CHANGELOG.md
release.sh

Backfill changelog

---

README.md
examples/datetimecol.py

Better docs and an example for DatetimeCol

---

examples/external_url_col.py

Related to https://github.com/plumdog/flask_table/issues/77#issuecomment-441400340

Add external_url_col example

---

examples/csrf.py

CSRF example
